parameters:
    secretName: ''
    keyVaultName: ''
    azureSubscriptionName: ''

steps:
- task: AzurePowerShell@5
  displayName: 'Update ${{ parameters.secretName}} in ${{ parameters.keyVaultName }}'
  inputs:
    azureSubscription: ${{ parameters.azureSubscriptionName }}
    ScriptType: inlineScript
    azurePowerShellVersion: latestVersion
    inline: |
      $secretvalue = ConvertTo-SecureString $env:Mapped_Secret -AsPlainText -Force
      $secret = Set-AzKeyVaultSecret -VaultName ${{ parameters.keyVaultName }} -Name ${{ parameters.secretName}} -SecretValue $secretValue
  env:
    Mapped_Secret: $(${{ parameters.secretName }})
