parameters:
- name: dockerFile
  type: string
  default: '**/Dockerfile'
- name: tags
  type: string
  default: 'latest'
- name: buildContext
  type: string
  default: '**'
- name: addPipelineData
  type: boolean
  default: true
- name: addBaseImageData
  type: boolean
  default: true
- name: containerRegistry
  type: string
- name: repository
  type: string
- name: serviceName
  type: string
steps:
- task: Docker@2
  displayName: 'Build Docker Image for ${{ parameters.serviceName }} and push to ${{ parameters.containerRegistry }}'
  inputs:
    containerRegistry: ${{ parameters.containerRegistry }}
    repository: ${{ parameters.repository }}
    command: 'buildAndPush'
    DockerFile: ${{ parameters.dockerFile }}
    tags: ${{ parameters.tags }}
    buildContext: ${{ parameters.buildContext }}
    addPipelineData: ${{ parameters.addPipelineData }}
    addBaseImageData: ${{ parameters.addBaseImageData }}
    
