parameters:
- name: dockerFile
  type: string
  default: '**/Dockerfile'
- name: tags
  type: string
  default: 'latest'
- name: buildContext
  type: string
  default: '**'
- name: arguments
  type: string
  default: ''
- name: addPipelineData
  type: boolean
  default: true
- name: addBaseImageData
  type: boolean
  default: true
- name: serviceName
  type: string
steps:
- task: Docker@2
  displayName: 'Build Docker Image for ${{ parameters.serviceName }}'
  inputs:
    command: 'build'
    DockerFile: ${{ parameters.dockerFile }}
    tags: ${{ parameters.tags }}
    buildContext: ${{ parameters.buildContext }}
    arguments: ${{ parameters.arguments }}
    addPipelineData: ${{ parameters.addPipelineData }}
    addBaseImageData: ${{ parameters.addBaseImageData }}
    
