parameters:
- name: versionSpec
  type: string
  default: '16.x'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: ${{ parameters.versionSpec }}
  displayName: 'Installing Node Version ${{ parameters.versionSpec }}'
