parameters:
- name: targetPath
  type: string
  default: '$(Build.ArtifactStagingDirectory)'
- name: artifactName
  type: string
  default: 'drop'

jobs:
- job: Publish_${{ parameters.artifactName }}
  steps:
   - template: ../tasks/ado_publish_pipeline_task.yml
     parameters:
        targetPath: ${{ parameters.targetPath }}
        artifactName: ${{ parameters.artifactName }}
