parameters:
- name: environmentName
  type: string
  default: 'dev'
- name: serviceName
  type: string
- name: terraformVersion
  type: string
  default: 'latest'
- name: additionalParameters
  type: object
  default: []
- name: dependsOn
  type: object
  default: []
jobs:
- job: 'buildTerraform_${{ parameters.environmentName }}'
  dependsOn: ${{parameters.dependsOn}}
  displayName: Build Terraform ${{ parameters.environmentName }}
  variables:
  - template: ../variables/azure_terraform_${{ parameters.environmentName }}_variables.yml
  steps:
  - template: ../tasks/terraform_install_task.yml
    parameters:
      terraformVersion: ${{ parameters.terraformVersion }}
      
  - template: ../tasks/terraform_init_task.yml
    parameters:
     serviceName: ${{ parameters.serviceName }}
     TerraformDirectory: ${{ variables.TerraformDirectory }}
     AzureSubscriptionServiceConnectionName: ${{ variables.AzureSubscriptionServiceConnectionName }}
     TerraformStateStorageAccountResourceGroupName: ${{ variables.TerraformStateStorageAccountResourceGroupName }}
     TerraformStateStorageAccountName: ${{ variables.TerraformStateStorageAccountName }}
     TerraformStateStorageAccountContainerName: ${{ variables.TerraformStateStorageAccountContainerName }}

  - template: ../tasks/terraform_plan_task.yml
    parameters:
      TerraformDirectory: ${{ variables.TerraformDirectory }}
      AzureSubscriptionServiceConnectionName: ${{ variables.AzureSubscriptionServiceConnectionName }}
      additionalParameters: ${{ parameters.additionalParameters }}
      publishPlanResults: 'CI - ${{ parameters.environmentName }} - ${{ parameters.serviceName }}'
