parameters:
  environmentObjects:
    - environmentName: 'dev'
      regionAbrvs: ['cus']
  serviceName: ''
  cacheNPM: true

stages:
- stage: '${{ parameters.serviceName }}_build'
  jobs:
  - template: ../jobs/nodejs_build_job.yml
    parameters:
      serviceName: ${{ parameters.serviceName }}
      cacheNPM: ${{ parameters.cacheNPM }}
